In [1]:
import pandas as pd

In [2]:
df_excel = pd.read_excel('Data/Final2023-24NCAAIWomensTennisWTAPointsSinceNCAAsMay262024.xlsx')
df_excel.head()

,NCAA's May 29 -,Thru 5/26/2024,Titles,Total,WTA Singles Points,WTA Doubles Points,Singles Events,Doubles Events,Total Events,Points Per Event,...,Doubles.7,S Events.7,D Events.7,Total Points.7,Total Events.8,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,1.0,NC State,12.0,3505,1532.0,1973.0,94.0,72.0,166,21.114458,...,37.0,5.0,8.0,37,13,Henderson,1.0,1.0,2.0,1.0
1,2.0,Oklahoma,4.0,1552,89.0,1463.0,43.0,59.0,102,15.215686,...,6.0,1.0,1.0,6,2,NaN,NaN,NaN,NaN,NaN
2,3.0,USC,4.0,750,333.0,417.0,53.0,27.0,80,9.375000,...,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN
3,4.0,Loyola Marymount,1.0,699,193.0,506.0,41.0,26.0,67,10.432836,...,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN
4,5.0,California,5.0,660,208.0,452.0,53.0,34.0,87,7.586207,...,3.0,4.0,3.0,6,7,NaN,NaN,NaN,NaN,NaN

## Top 10 singles players

In [3]:
columns_points = ['Singles', 'Singles.1', 'Singles.2', 'Singles.3', 'Singles.4', 'Singles.5', 'Singles.6', 'Singles.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data across the selected columns
all_values = df_excel[columns_points].values.flatten()
all_players = df_excel[columns_players].values.flatten()

# We will flatten the 'Thru 5/26/2024' column to match the shape of the points and players
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_points)).values

# Combine points, players, and school names
points_players_schools = list(zip(all_values, all_players, all_schools))

# Sort by points and get the top 10 values with corresponding players and school names
top_10_points_players_schools = sorted(points_players_schools, key=lambda x: x[0], reverse=True)[:10]

# Convert to DataFrame
df_top_10 = pd.DataFrame(top_10_points_players_schools, columns=['Singles Points', 'Player', 'School'])

# Display the DataFrame
df_top_10

   Singles Points          Player            School
0          1269.0        Shnaider          NC State
1           226.0            Sieg               USC
2           173.0           Naklo        Iowa State
3           171.0  Miroshnichenko  Loyola Marymount
4           165.0         Crawley    North Carolina
5           158.0        A. Smith          NC State
6           139.0         Giavara        California
7           129.0            Beck              Duke
8           121.0           Vecic           Georgia
9           114.0       Branstine         Texas A&M

In [4]:
df_top_10.to_csv('Data/Data_for_Tableau/top10players_singlespoints.csv', index=False)

## Top 10 doubles players

In [5]:
columns_points = ['Doubles', 'Doubles.1', 'Doubles.2', 'Doubles.3', 'Doubles.4', 'Doubles.5', 'Doubles.6', 'Doubles.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data across the selected columns
all_values = df_excel[columns_points].values.flatten()
all_players = df_excel[columns_players].values.flatten()

# We will flatten the 'Thru 5/26/2024' column to match the shape of the points and players
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_points)).values

# Combine points, players, and school names
points_players_schools = list(zip(all_values, all_players, all_schools))

# Sort by points and get the top 10 values with corresponding players and school names
top_10_points_players_schools = sorted(points_players_schools, key=lambda x: x[0], reverse=True)[:10]

# Convert to DataFrame
df_top_10 = pd.DataFrame(top_10_points_players_schools, columns=['Doubles Points', 'Player', 'School'])

# Display the DataFrame
df_top_10

   Doubles Points          Player            School
0           751.0        Shnaider          NC State
1           614.0       I. Corley          Oklahoma
2           605.0        A. Smith          NC State
3           564.0        C.Corley          Oklahoma
4           463.0  Miroshnichenko  Loyola Marymount
5           376.0         Giavara        California
6           294.0        Rencheli          NC State
7           278.0         Markham         Wisconsin
8           256.0          Sleeth          Oklahoma
9           235.0        Lemaitre               TCU

In [6]:
df_top_10.to_csv('Data/Data_for_Tableau/top10players_doublespoints.csv', index=False)

## Top 10 Total Points players

In [7]:
columns_points = ['Total Points', 'Total Points.1', 'Total Points.2', 'Total Points.3', 'Total Points.4', 'Total Points.5', 'Total Points.6', 'Total Points.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data across the selected columns
all_values = df_excel[columns_points].values.flatten()
all_players = df_excel[columns_players].values.flatten()

# We will flatten the 'Thru 5/26/2024' column to match the shape of the points and players
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_points)).values

# Combine points, players, and school names
points_players_schools = list(zip(all_values, all_players, all_schools))

# Sort by points and get the top 10 values with corresponding players and school names
top_10_points_players_schools = sorted(points_players_schools, key=lambda x: x[0], reverse=True)[:10]

# Convert to DataFrame
df_top_10 = pd.DataFrame(top_10_points_players_schools, columns=['Singles Points', 'Player', 'School'])

# Display the DataFrame
df_top_10

   Singles Points          Player            School
0            2020        Shnaider          NC State
1             763        A. Smith          NC State
2             634  Miroshnichenko  Loyola Marymount
3             619       I. Corley          Oklahoma
4             581        C.Corley          Oklahoma
5             515         Giavara        California
6             448            Sieg               USC
7             349         Markham         Wisconsin
8             337        Lemaitre               TCU
9             320          Sleeth          Oklahoma

In [8]:
df_top_10.to_csv('Data/Data_for_Tableau/top10players_totalpoints.csv', index=False)

## Top 10 singles teams (University teams that have the most singles points)

In [36]:
import pandas as pd

# Assuming 'df_excel' is your original DataFrame

# Define the columns for players and WTA singles points
columns_singles_points = ['Singles', 'Singles.1', 'Singles.2', 'Singles.3', 'Singles.4', 'Singles.5', 'Singles.6', 'Singles.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data: extracting player names and their corresponding WTA singles points
singles_values = df_excel[columns_singles_points].values.flatten()  # WTA Singles Points
all_players = df_excel[columns_players].values.flatten()  # Player Names
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_singles_points)).values  # Schools

# Create a DataFrame with the required columns
required_columns_df = pd.DataFrame({
    'School': all_schools,       # Schools (one per player)
    'Player': all_players,       # Player names
    'WTA Singles Points': singles_values  # Corresponding singles points
})

# Drop rows where 'Player' or 'WTA Singles Points' are null
required_columns_df = required_columns_df.dropna(subset=['Player', 'WTA Singles Points'])

# Display the result
print(required_columns_df)

# Optionally, save to CSV for Tableau
# required_columns_df.to_csv('required_columns_for_tableau.csv', index=False)


# Optionally, save to CSV for Tableau
required_columns_df.to_csv('Data/Data_for_Tableau/SinglesPoints.csv', index=False)

       School       Player  WTA Singles Points
0    NC State     Shnaider              1269.0
1    NC State     A. Smith               158.0
2    NC State      Rajecki                38.0
3    NC State     Rencheli                15.0
4    NC State       Abrams                 0.0
..        ...          ...                 ...
675   Alabama  Parkhomenko                 0.0
676   Alabama        Hiser                 0.0
677   Alabama     Miliceic                 0.0
678   Alabama      K Pitak                 0.0
679   Alabama         Kern                 0.0

[651 rows x 3 columns]

In [ ]:
required_columns_df

In [25]:
top10teams_singlesteams = df_excel[['Thru 5/26/2024', 'WTA Singles Points ']].sort_values(by='WTA Singles Points ', ascending=False)[:85]
top10teams_singlesteams

    Thru 5/26/2024  WTA Singles Points
0         NC State               1532.0
2              USC                333.0
8          Georgia                298.0
7        Texas A&M                212.0
4       California                208.0
..             ...                  ...
63             LSU                  0.0
52             UNF                  0.0
61     North Texas                  0.0
53  Boston College                  0.0
84         Alabama                  0.0

[85 rows x 2 columns]

In [26]:
top10teams_singlesteams.to_csv('Data/Data_for_Tableau/top10teams_singlesteams.csv', index=False)

## Top 10 doubles teams (University teams that have the most doubles points)

In [38]:
# Define the columns for players and WTA doubles points
columns_doubles_points = ['Doubles', 'Doubles.1', 'Doubles.2', 'Doubles.3', 'Doubles.4', 'Doubles.5', 'Doubles.6', 'Doubles.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data: extracting player names and their corresponding WTA doubles points
doubles_values = df_excel[columns_doubles_points].values.flatten()  # WTA Doubles Points
all_players = df_excel[columns_players].values.flatten()  # Player Names
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_doubles_points)).values  # Schools

# Create a DataFrame with the required columns
required_columns_df = pd.DataFrame({
    'School': all_schools,       # Schools (one per player)
    'Player': all_players,       # Player names
    'WTA Doubles Points': doubles_values  # Corresponding doubles points
})

# Drop rows where 'Player' or 'WTA Doubles Points' are null
required_columns_df = required_columns_df.dropna(subset=['Player', 'WTA Doubles Points'])

# Display the result
print(required_columns_df)

# Optionally, save to CSV for Tableau
# required_columns_df.to_csv('required_columns_for_tableau.csv', index=False)

# Optionally, save to CSV for Tableau
required_columns_df.to_csv('Data/Data_for_Tableau/DoublesPoints.csv', index=False)

       School       Player  WTA Doubles Points
0    NC State     Shnaider               751.0
1    NC State     A. Smith               605.0
2    NC State      Rajecki               171.0
3    NC State     Rencheli               294.0
4    NC State       Abrams                 0.0
..        ...          ...                 ...
675   Alabama  Parkhomenko                 0.0
676   Alabama        Hiser                 0.0
677   Alabama     Miliceic                 0.0
678   Alabama      K Pitak                 0.0
679   Alabama         Kern                 0.0

[651 rows x 3 columns]

In [11]:
top10teams_doublesteams = df_excel[['Thru 5/26/2024', 'WTA Doubles Points']].sort_values(by='WTA Doubles Points', ascending=False)[:10]
top10teams_doublesteams

      Thru 5/26/2024  WTA Doubles Points
0           NC State              1973.0
1           Oklahoma              1463.0
3   Loyola Marymount               506.0
4         California               452.0
2                USC               417.0
9          Wisconsin               311.0
6                TCU               309.0
5             Auburn               306.0
10              UCLA               215.0
11           Ohio St               204.0

In [12]:
top10teams_doublesteams.to_csv('Data/Data_for_Tableau/top10teams_doublesteams.csv', index=False)

## Top 10 Teams by Ranking (Titles)

In [9]:
top10teams_titles = df_excel[['Thru 5/26/2024', 'Titles']].sort_values(by='Titles', ascending=False)[:10]
top10teams_titles

    Thru 5/26/2024  Titles
0         NC State    12.0
7        Texas A&M     6.0
13  North Carolina     5.0
4       California     5.0
5           Auburn     5.0
16     Oklahoma St     5.0
2              USC     4.0
1         Oklahoma     4.0
26             UCF     4.0
14      Iowa State     4.0

In [12]:
result = []

for index, row in top10teams_titles.iterrows():
    for count in range(1, int(row['Titles']) + 1):
        result.append({'School': row['Thru 5/26/2024'], 'Count': count})

# Convert the result to a new DataFrame
result_df = pd.DataFrame(result)

In [14]:
result_df.to_csv('Data/Data_for_Tableau/top10teams_titlescountdown.csv', index=False)

## Top 10 Teams by Points Per Event

In [15]:
top10teams_pointsperevent = df_excel[['Thru 5/26/2024', 'Points Per Event']].sort_values(by='Points Per Event', ascending=False)[:10]
top10teams_pointsperevent

      Thru 5/26/2024  Points Per Event
0           NC State         21.114458
1           Oklahoma         15.215686
13    North Carolina         13.523810
19          Stanford         11.000000
3   Loyola Marymount         10.432836
2                USC          9.375000
15              Duke          8.966667
7          Texas A&M          8.333333
24    South Carolina          8.142857
4         California          7.586207

In [16]:
top10teams_pointsperevent.to_csv('Data/Data_for_Tableau/top10teams_points_per_event.csv', index=False)

## National Ranking for Each NCSU Player by Singles, Doubles, and Total Points

In [17]:
columns_doubles_points = ['Doubles', 'Doubles.1', 'Doubles.2', 'Doubles.3', 'Doubles.4', 'Doubles.5', 'Doubles.6', 'Doubles.7']
columns_singles_points = ['Singles', 'Singles.1', 'Singles.2', 'Singles.3', 'Singles.4', 'Singles.5', 'Singles.6', 'Singles.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data across all universities
doubles_values = df_excel[columns_doubles_points].values.flatten()  # Doubles points across all players
singles_values = df_excel[columns_singles_points].values.flatten()  # Singles points across all players
all_players = df_excel[columns_players].values.flatten()  # Player names across all universities
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_doubles_points)).values  # University names, repeated for all players

# Combine doubles points, singles points, players, and school names into a DataFrame
points_players_schools = pd.DataFrame({
    'Player': all_players,
    'School': all_schools,
    'Doubles Points': doubles_values,
    'Singles Points': singles_values
})

# Add a column for Total Points (sum of Doubles and Singles Points)
points_players_schools['Total Points'] = points_players_schools['Doubles Points'] + points_players_schools['Singles Points']

# Rank players by doubles points across all WTA players
points_players_schools['Doubles Rank'] = points_players_schools['Doubles Points'].rank(ascending=False, method='min')

# Rank players by singles points across all WTA players
points_players_schools['Singles Rank'] = points_players_schools['Singles Points'].rank(ascending=False, method='min')

# Rank players by total points across all WTA players
points_players_schools['Total Rank'] = points_players_schools['Total Points'].rank(ascending=False, method='min')

# Filter for NC State players
nc_state_players = points_players_schools[points_players_schools['School'] == 'NC State']

# Sort NC State players by their total points rank, then doubles and singles ranks
nc_state_players_ranked = nc_state_players.sort_values(['Total Rank', 'Doubles Rank', 'Singles Rank'])

# Display the ranked NC State players for doubles, singles, and total points
nc_state_players_ranked

,Player,School,Doubles Points,Singles Points,Total Points,Doubles Rank,Singles Rank,Total Rank
0,Shnaider,NC State,751.0,1269.0,2020.0,1.0,1.0,1.0
1,A. Smith,NC State,605.0,158.0,763.0,3.0,6.0,2.0
3,Rencheli,NC State,294.0,15.0,309.0,7.0,56.0,11.0
2,Rajecki,NC State,171.0,38.0,209.0,12.0,31.0,17.0
6,Zyryanova,NC State,94.0,34.0,128.0,23.0,32.0,27.0
5,Dittmann,NC State,21.0,18.0,39.0,65.0,47.0,62.0
7,N. Miller,NC State,37.0,0.0,37.0,53.0,144.0,63.0
4,Abrams,NC State,0.0,0.0,0.0,163.0,144.0,190.0

In [18]:
nc_state_players_ranked.to_csv('Data/Data_for_Tableau/nc_state_players_ranked.csv', index=False)

## Singles and Doubles Points

In [5]:
import pandas as pd

# Assuming 'df_excel' is your original DataFrame

# Define the columns for players, doubles, singles, and total points
columns_doubles_points = ['Doubles', 'Doubles.1', 'Doubles.2', 'Doubles.3', 'Doubles.4', 'Doubles.5', 'Doubles.6', 'Doubles.7']
columns_singles_points = ['Singles', 'Singles.1', 'Singles.2', 'Singles.3', 'Singles.4', 'Singles.5', 'Singles.6', 'Singles.7']
columns_total_points = ['Total Points', 'Total Points.1', 'Total Points.2', 'Total Points.3', 'Total Points.4', 'Total Points.5', 'Total Points.6', 'Total Points.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data: extracting player names, doubles, singles, and total points
doubles_values = df_excel[columns_doubles_points].values.flatten()  # WTA Doubles Points
singles_values = df_excel[columns_singles_points].values.flatten()  # WTA Singles Points
total_values = df_excel[columns_total_points].values.flatten()  # Total Points
all_players = df_excel[columns_players].values.flatten()  # Player Names
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_doubles_points)).values  # Schools

# Create a DataFrame with the required columns
required_columns_df = pd.DataFrame({
    'School': all_schools,         # Schools (one per player)
    'Player': all_players,         # Player names
    'WTA Doubles Points': doubles_values,  # Corresponding doubles points
    'WTA Singles Points': singles_values,  # Corresponding singles points
    'Total Points': total_values   # Total Points by player
})

# Drop rows where 'Player', 'WTA Doubles Points', 'WTA Singles Points', or 'Total Points' are null or 0
required_columns_df = required_columns_df.dropna(subset=['Player', 'WTA Doubles Points', 'WTA Singles Points', 'Total Points'])
required_columns_df = required_columns_df[required_columns_df['Total Points'] > 0]

# Display the result
required_columns_df

# Optionally, save to CSV for Tableau
required_columns_df.to_csv('Data/Data_for_Tableau/singlesDoubles.csv', index=False)

## Singles Doubles Events

In [6]:
import pandas as pd

# Assuming 'df_excel' is your original DataFrame

# Define the columns for players, doubles events, singles events, and total events
columns_doubles_events = ['D Events', 'D Events.1', 'D Events.2', 'D Events.3', 'D Events.4', 'D Events.5', 'D Events.6', 'D Events.7']
columns_singles_events = ['S Events', 'S Events.1', 'S Events.2', 'S Events.3', 'S Events.4', 'S Events.5', 'S Events.6', 'S Events.7']
columns_total_events = ['Total Events', 'Total Events.1', 'Total Events.2', 'Total Events.3', 'Total Events.4', 'Total Events.5', 'Total Events.6', 'Total Events.7']
columns_players = ['Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5', 'Player 6', 'Player 7', 'Player 8']

# Flatten the data: extracting player names, doubles events, singles events, and total events
doubles_events_values = df_excel[columns_doubles_events].values.flatten()  # Doubles Events
singles_events_values = df_excel[columns_singles_events].values.flatten()  # Singles Events
total_events_values = df_excel[columns_total_events].values.flatten()  # Total Events
all_players = df_excel[columns_players].values.flatten()  # Player Names
all_schools = df_excel['Thru 5/26/2024'].repeat(len(columns_doubles_events)).values  # Schools

# Create a DataFrame with the required columns
required_columns_df = pd.DataFrame({
    'School': all_schools,         # Schools (one per player)
    'Player': all_players,         # Player names
    'Doubles Events': doubles_events_values,  # Corresponding doubles events
    'Singles Events': singles_events_values,  # Corresponding singles events
    'Total Events': total_events_values   # Total Events by player
})

# Drop rows where 'Player', 'Doubles Events', 'Singles Events', or 'Total Events' are null or 0
required_columns_df = required_columns_df.dropna(subset=['Player', 'Doubles Events', 'Singles Events', 'Total Events'])
required_columns_df = required_columns_df[required_columns_df['Total Events'] > 0]

# Display the result
required_columns_df

# Optionally, save to CSV for Tableau
required_columns_df.to_csv('Data/Data_for_Tableau/singlesDoublesEvents.csv', index=False)

In [7]:
required_columns_df

             School      Player  Doubles Events  Singles Events  Total Events
0          NC State    Shnaider            13.0            26.0           166
1          NC State    A. Smith            25.0            30.0            39
2          NC State     Rajecki             7.0            10.0            55
3          NC State    Rencheli             5.0             4.0            17
4          NC State      Abrams             0.0             0.0             9
..              ...         ...             ...             ...           ...
601          Denver     Beltran             0.0             0.0             1
608         Pacific       Kosan             0.0             1.0             1
609         Pacific        Main             0.0             0.0             1
616  Louisiana Tech  Schukneckt             0.0             0.0             1
619  Louisiana Tech        Nash             0.0             0.0             1

[277 rows x 5 columns]